production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
  options:
    raise_not_found_error: false
    
# heroku addons:add mongohq