development:
  clients:
    default:
#      uri: <%= ENV['MONGOHQ_URL'] %>      
      database: rails_project_development
      hosts:
        - 127.0.0.1:27017
      options:
  options:
    raise_not_found_error: false # by rems

test:
  clients:
    default:
      database: testing
      hosts:
        - 127.0.0.1:27017
      options:
  options:
    raise_not_found_error: false # by rems

production:
  clients:
    default:
      database: drgcms
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
