development:
  sessions:
    default:
      database: rails_project_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false # by rems

test:
  sessions:
    default:
      database: rails_project_test
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false # by rems

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    raise_not_found_error: false
