development:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>      
#      database: rails_project_development
#      hosts:
#        - localhost:27017
      options:
  options:
    raise_not_found_error: false # by rems

test:
  clients:
    default:
      database: testi
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false # by rems

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    raise_not_found_error: false
