production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0    
  options:
    raise_not_found_error: false
    
# heroku addons:add mongohq